---
- name: 'Ensure packages'
  ansible.builtin.package:
    name: 'unbound'
    state: 'present'
  register: 'unbound_installed'

- name: 'Ensure firewalld'
  ansible.posix.firewalld:
    service: 'dns'
    state: 'enabled'
    permanent: true
    immediate: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: 'Remove default config'  # noqa no-handler
  ansible.builtin.file:
    path: "{{ default_conf }}"
    state: 'absent'
  loop:
    - '/etc/unbound/unbound.conf.d'
    - '/etc/unbound/conf.d'
    - '/etc/unbound/keys.d'
    - '/etc/unbound/local.d'
  loop_control:
    loop_var: 'default_conf'
  when: unbound_installed['changed']

- name: 'Ensure root.key'
  ansible.builtin.command: /usr/sbin/unbound-anchor -a /var/lib/unbound/root.key
  register: 'unbound_root_key_update'
  changed_when: unbound_root_key_update['rc'] == 1
  failed_when: unbound_root_key_update['rc'] > 1

- name: 'Ensure unbound.conf'
  ansible.builtin.template:
    src: 'unbound.conf.j2'
    dest: '/etc/unbound/unbound.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    validate: '/usr/sbin/unbound-checkconf %s'
  notify: 'restart unbound'

- name: 'Ensure service'
  ansible.builtin.systemd:
    name: 'unbound'
    enabled: true
    state: 'started'
