---
- name: 'Converge'
  hosts: 'all'
  vars:
    - dns_recursor_stub_zones:
        - name: 'example.com.'
          upstream: '10.1.1.1'
          secure: false
        - name: 'example.net.'
          upstream: '10.1.1.1'
    - dns_recursor_forward_zones:
        - name: 'example.org'
          upstream: '10.1.1.1'
          secure: false
        - name: 'example.nl.'
          upstream: '10.1.1.1'
    - dns_recursor_local_records:
        - name: 'host.example.eu'
          type: 'A'
          value: '10.1.1.1'
  tasks:
    - name: 'Run role'
      import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
