---
- name: 'Update package sources'
  hosts: 'all'
  tasks:
    - name: 'Update APT cache'
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: 'Update YUM cache'
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: 'Ensure dependencies'
      ansible.builtin.package:
        name:
          - 'bind-utils'
          - 'epel-release'
        state: 'present'
      when: ansible_facts['os_family'] == 'RedHat'
      check_mode: false

    - name: 'Ensure dependencies'
      ansible.builtin.package:
        name: 'bind9-dnsutils'
        state: 'present'
      when: ansible_facts['os_family'] == 'Debian'
